### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by japhib** [japhib/PieceOfSheet#1]
![screenshot from 2015-12-10 22-59-09](https://cloud.githubusercontent.com/assets/11890284/11737024/f735ee9e-9f91-11e5-8be4-f05e3276edf2.png)
![screenshot from 2015-12-10 23-02-00](https://cloud.githubusercontent.com/assets/11890284/11737039/153dd74e-9f92-11e5-9dc7-b873c4a5bba3.png)
![screenshot from 2015-12-10 23-02-16](https://cloud.githubusercontent.com/assets/11890284/11737040/173c1ce0-9f92-11e5-827e-d8f5335f85bb.png)
![screenshot from 2015-12-10 23-03-20](https://cloud.githubusercontent.com/assets/11890284/11737049/3b4aa278-9f92-11e5-9bba-61b2564e7b8c.png)
![screenshot from 2015-12-10 23-04-17](https://cloud.githubusercontent.com/assets/11890284/11737056/5da6ca18-9f92-11e5-8d0b-f6f134484122.png)
![screenshot from 2015-12-10 23-04-40](https://cloud.githubusercontent.com/assets/11890284/11737059/6b946b08-9f92-11e5-9838-3625bd3aaa0c.png)

**Comment by japhib** [comment]
![screenshot from 2015-12-10 23-05-12](https://cloud.githubusercontent.com/assets/11890284/11737066/7c6bc214-9f92-11e5-8cda-51873aee082e.png)

**Comment by dcox34** [comment]
![comments1](https://cloud.githubusercontent.com/assets/14239919/11741072/d19b4004-9fb3-11e5-8cfc-16af5936dbd8.png)
![comments2](https://cloud.githubusercontent.com/assets/14239919/11741075/d43ca488-9fb3-11e5-9728-b48c43e273e6.png)

**Comment by sebrantley** [comment]
![image](https://cloud.githubusercontent.com/assets/13441798/11742936/e10bf7f6-9fc0-11e5-8c1e-32322fbb8b56.png)

**Comment by sebrantley** [comment]
![image](https://cloud.githubusercontent.com/assets/13441798/11743047/b3fefb22-9fc1-11e5-99ed-a80445581ada.png)

**Comment by sebrantley** [comment]
![image](https://cloud.githubusercontent.com/assets/13441798/11743147/6873bd86-9fc2-11e5-8b2c-921459a61c5f.png)
